version: '3.8'

services:
  wordpress:
    image: ghcr.io/fastwebapp/wordpress:latest
    depends_on:
      - mysql
    ports:
      - 80:80
    working_dir: /var/www/html/wp
    volumes:
      - ./docker:/docker
      - ./public:/var/www/html
      - ./vendor:/var/www/vendor
      - ./.env:/var/www/.env
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        if (WP_DEBUG) {
          define('WP_DEBUG_LOG', true);
          define('WP_DEBUG_DISPLAY', false);
        }

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - phpmyadmin:/sessions
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mailhog:/tmp
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp

volumes:
  phpmyadmin:
    driver: local
  mysql:
    driver: local
  mailhog:
    driver: local
